some quick checks

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -178,7 +178,7 @@ jobs:
           
   build-all-production-deps:
     name: build-all-production-deps
-    if: ${{ inputs.github_event_name == 'push' || inputs.github_event_name == 'merge_group' || (inputs.github_event_name == 'pull_request' && inputs.github_event_pull_request_head_repo_id == 383289760) }}
+    if: ${{ inputs.github_event_name == 'merge_group' || (inputs.github_event_name == 'pull_request' && inputs.github_event_pull_request_head_repo_id == 383289760) }}
     needs: 
       - privilege-check
       - lfs-check
@@ -497,23 +497,26 @@ jobs:
 
   draft-release-check:
       name: "draft-release-check"
+      if: ${{ failure() || cancelled() || success() }}
       continue-on-error: false
       runs-on: ubuntu-latest
       needs:
-        - build-all-benchmarks-packages
-        - build-all-ci-packages
-        - build-all-docs-packages
+        # - build-all-benchmarks-packages
+        # - build-all-ci-packages
+        # - build-all-docs-packages
         - build-all-misc-packages
-        - build-all-production-deps
+        # - build-all-production-deps
         - dependency-review
         - nix-flake-check
       steps:
-        - run: |
-            echo "probably no bugs"
         - if: ${{ cancelled() }}
           run: |
+            echo "Cannot skip this job"
+        - if: ${{ failure() }}
+          run: |
+            echo "One of dependencies failed"            
             exit 42
-        
+            
   draft-release-artifacts:
     name: "draft-release-artifacts"    
     runs-on:
@@ -521,7 +524,7 @@ jobs:
       - x64-cute
     needs:
       - draft-release-check
-    if: ${{ inputs.github_event_name == 'pull_request' && inputs.github_event_pull_request_head_repo_id == 383289760 }}  
+    if: ${{ inputs.github_event_name == 'push' }}  
     permissions:  
       pull-requests: write
       contents: write      
@@ -565,7 +568,7 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           draft: true
-          prerelease: true
+          prerelease: false
           fail_on_unmatched_files: true
           generate_release_notes: true
           body_path: release-artifacts/release.txt
@@ -666,6 +669,7 @@ jobs:
       
   devnet-integration-tests:
     name: Devnet integration tests [FLAKY]
+    if: ${{ inputs.github_event_name == 'merge_group' || (inputs.github_event_name == 'pull_request_target' && inputs.github_event_pull_request_head_repo_id != 383289760) || (inputs.github_event_name == 'pull_request' && inputs.github_event_pull_request_head_repo_id == 383289760) }}    
     needs: 
       - build-all-ci-packages
     strategy:
